In [60]:
import pandas as pd
import numpy as np
import logging
from sklearn.model_selection import train_test_split    
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [61]:
# Load the dataset
df = pd.read_csv('Sonar_dataset.csv',header=None)


In [62]:

X = df[df.columns[0:60]].values

In [63]:
X

array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
       [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [64]:
Y = df[60].values

In [65]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, stratify=Y, random_state=1)

In [66]:
X_test.shape
X_train.shape

(187, 60)

In [67]:
model =  LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [68]:
print(X_train)

[[0.0414 0.0436 0.0447 ... 0.0077 0.0246 0.0198]
 [0.0123 0.0022 0.0196 ... 0.0058 0.0047 0.0071]
 [0.0152 0.0102 0.0113 ... 0.0011 0.0034 0.0033]
 ...
 [0.0117 0.0069 0.0279 ... 0.0062 0.0026 0.0052]
 [0.115  0.1163 0.0866 ... 0.0141 0.0068 0.0086]
 [0.0187 0.0346 0.0168 ... 0.0115 0.0193 0.0157]]


In [69]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [70]:
training_data_accuracy

0.8342245989304813

In [71]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)


In [72]:
input_values = (0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,0.1609,0.1582,0.2238,0.0645,0.0660,0.2273,0.3100,0.2999,0.5078,0.4797,0.5783,0.5071,0.4328,0.5550,0.6711,0.6415,0.7104,0.8080,0.6791,0.3857,0.1307,0.2604,0.5121,0.7547,0.8537,0.8507,0.6692,0.6097,0.4943,0.2744,0.0510,0.2834,0.2825,0.4256,0.2641,0.1386,0.1051,0.1343,0.0383,0.0324,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032)
data_array = np.asarray(input_values)
reshape_data = data_array.reshape(1,-1)
output = model.predict(reshape_data)
prediction_map = {'R': "It's a Rock", 'M': "It's a mine"}
print(prediction_map.get(output[0], "Unknown prediction"))

It's a Rock
